### ISSUE TITLE
constant 3735928559 overflows int

### ISSUE THREAD

**Issue by jaeyeom** [HouzuoGuo/tiedot#68] opened 2014-08-24 23:54 UTC
github.com/HouzuoGuo/tiedot/data/hashtable.go:43: constant 3735928559 overflows int

I am compiling tiedot from ARM based Linux Raspbian on my Raspberry Pi and I got the above message. Go version 1.3.

**Comment by ktw** [comment] 2015-11-17 13:27
Hi.

Will this 32 bit branch be updated to version 3.2 at some point?
I am trying to cross compile for a Scaleway C1 instance. (ARMv7 Cortex-A9)

**Comment by HouzuoGuo** [comment] 2015-11-17 14:20
hello @ktw, actually there isn't a big difference between 32bit branch based on 3.1.3 and the latest release 3.2.

3.2 introduces optionally enabled JWT for authorizing API calls, it fixes a performance issue observed on certain OS/FS combinations, and removes web control panel.

Is there a feature you need from 3.2? I can backport it for you if you like.

**Comment by mmindenhall** [comment] 2015-11-17 15:27
I was also using tiedot in a prototype earlier in the year, and it looked to me like the 32-bit branch would not be needed if a few `int` declarations were simply changed to `int64` in the codebase.  If that's the case, why not do that instead of backport and maintain a separate branch?

**Comment by HouzuoGuo** [comment] 2015-11-17 16:43
@mmindenhall that's a good point, indeed I should have done that from the very beginning.
all right, let's do it this way in master.

**Comment by WinterPhoenix** [comment] 2016-05-17 18:23
Any updates on this? I understand that it's probably low priority but I'm running into it as well.

**Comment by HouzuoGuo** [comment] 2016-05-18 06:32
Hello WinterPhoenix. Could you please give "32bit" branch a try and see if that one works for you?

**Comment by WinterPhoenix** [comment] 2016-05-18 17:50
Sure, I expect that the 32bit branch should do what I need it to do. I just wanted to see if a fix for this was imminent before I spent time switching to the branch. I saw that it was reopened in November and figured I'd check. Thanks!

**Comment by archey** [comment] 2017-02-03 18:00
Any update on this issue? It would be nice if this could be fixed.

**Comment by HouzuoGuo** [comment] 2017-02-07 09:30
@archey very sorry about this, it's been an outstanding bug for nearly three years already.

I have trouble finding a 32-bit system to run some tests, if you could do me a small favour, please try this quick & dirty workaround - remove the entire "interger-smear" section from https://github.com/HouzuoGuo/tiedot/blob/master/data/hashtable.go#L39 and run its tests. The hash table will appear somewhat unbalanced, but should remain functional. If that workaround helps, the function `HashKey` should be elevated into its own arch depent source file.

CC @gertcuykens @davesters @omeid @Dr-Terrible @Komosa & all collaborators - what do you recommend?

**Comment by archey** [comment] 2017-02-07 15:49
@HouzuoGuo Ill spin up  a 32bit vm and test it out and let you know.

**Comment by archey** [comment] 2017-02-10 01:52
@HouzuoGuo is there any reason why you cant change the int to uint64 that would allow it to run 32bit systems?

**Comment by HouzuoGuo** [comment] 2017-02-10 07:55
You're right, that should have been done from the very beginning and there's no good reason against it. In fact I began experimenting with it - along with a home grown RPC protocol, in a separate branch (https://github.com/HouzuoGuo/tiedot/blob/singlethread/data/partition.go).

But altering it on master branch would be risky, there will be a lot of compilation errors caused by incompatible types.

Now I regret not having done so from very beginning, even more.

**Comment by archey** [comment] 2017-02-10 12:53
@HouzuoGuo I have it compiling on arm and 386 by moving that hashkey func to its own go file like doing hash32.go and hash64.go then using // +build params to build the specific version of arm or 386 but not build the 64bit version. I had to remove the buildconstraint.go temporarily to get it to build. I started to run the tests, but my rootfs on this box is only a few gigs so it ran out of space.

**Comment by HouzuoGuo** [comment] 2017-02-10 14:58
thanks very much for the feedback.

the other thing I regret is that tiedot allocates disk space way too aggressively, since you have a 32-bit environment handy for testing, would you mind to also tweak these constants:

https://github.com/HouzuoGuo/tiedot/blob/master/data/collection.go#L24
Change `COL_FILE_GROWTH` to `8 * 1048576`

https://github.com/HouzuoGuo/tiedot/blob/master/data/hashtable.go#L22
- Change `HT_FILE_GROWTH` to `8 * 1048576`
- `INITIAL_BUCKETS` to `16384`
- `HASH_BITS` to `14`

Looking forward to your feedback!

**Comment by archey** [comment] 2017-02-10 15:27
@HouzuoGuo let me give it a shot and Ill get back to you

**Comment by archey** [comment] 2017-02-10 15:48
@HouzuoGuo all built and tests pass with 4.989s with the changes I made and the changes you requested. In my hash32.go file I still commented out the integer-smear function

**Comment by archey** [comment] 2017-02-10 17:14
@HouzuoGuo heres the benchmark results if your curious

https://gist.github.com/archey/feb0d76e3c372a31eb01cba5fc883ddc

**Comment by HouzuoGuo** [comment] 2017-02-11 15:00
Many thanks for your feedback, that looks quite good! I just put you into collaborators list, would you mind pushing the code to master please?

**Comment by archey** [comment] 2017-02-11 15:03
I could make a pr, but Ill push to it if you'd like one moment

**Comment by archey** [comment] 2017-02-11 15:12
@HouzuoGuo changes are pushed to master I removed the buildconstraint.go as it would of caused build issues for people.

**Comment by HouzuoGuo** [comment] 2017-02-11 18:15
@archey could you please move the changed constants into hash32/64.go as well? Otherwise those changes will cause existing databases to malfunction.

**Comment by HouzuoGuo** [comment] 2017-02-11 18:16
By the way, if you've also made changes to collection.go, please push it as well, and keep the modified constants also in the conditionally compiled .go files.

**Comment by archey** [comment] 2017-02-11 18:46
Yeah let me get those issues fixed, Im still new to golang. I'll fix it up and see if the next push will be better.

**Comment by archey** [comment] 2017-02-11 19:57
@HouzuoGuo the last push should be better I made a modified hashtable32 with the constants and a modified collection32 with the constants, they will only build on 386 and arm. Let me know if that was wrong, I can revert it and start over. It just made more sense to me that way.

**Comment by HouzuoGuo** [comment] 2017-02-12 07:23
Oh I see you made the entire file collection.go and hashtable.go arch-dependent, this is OK too but then there is too much duplication between the arch dependent files. Let me fix it later today.

**Comment by archey** [comment] 2017-02-12 14:01
@HouzuoGuo yeah my bad I can go back and fix it again, it just made more sense please fix whatever youd like

**Comment by HouzuoGuo** [comment] 2017-02-12 14:30
No worries at all, I fixed it in master, please run tests in your 32-bit system and see if they still succeed. If so, this bug report may be finally closed.

**Comment by archey** [comment] 2017-02-12 14:31
Will do

**Comment by archey** [comment] 2017-02-12 15:22
@HouzuoGuo builds fine and tests pass, with flying colors

**Comment by HouzuoGuo** [comment] 2017-02-12 17:46
thanks very much, I'm glad to finally resolve this issue after 3 years 🧀

**Closed by HouzuoGuo** 2017-02-12 17:46 UTC

**Comment by archey** [comment] 2017-02-12 17:48
@HouzuoGuo no problem I wish I had seen it sooner. I think spinning up a i686 vm would of worked as well
